jest.config.js
src/__test__/m.spec.ts
src/m.ts

refactor: update m method

---

package.json

**Description:**
As this package was made by you (both) we should update this part of the documentation.
**Status**

docs: update contributors

---

README.md

**Description:**
This makes the license easily visible to everyone who came here :)

docs: create a license session

---

benchmarks/conditional-render.js
benchmarks/index.html
benchmarks/list-render.js
benchmarks/text-interop.js
jest.config.js
jest.setup.ts
src/patch.ts
src/schedule.ts
src/structs.ts
tsconfig.json

 Fixed scheduler

---

README-zh_CN.md
README.md

Add README-zh_CN.md file

---

package.json
pnpm-lock.yaml
src/drivers/props.ts

fix(#153): props that dont equal attribute names

---

packages/block/block.ts
packages/ssr/refresh.ts

fix(#169): use relative paths under packages/*

---

src/react/compat.ts

refactor(react): remove transition

---

src/million/types.ts

refactor(hooks): used mapped type

---

src/million/createElement.ts
src/million/drivers/useProps.ts

optimize judgment conditions
**Status**

refactor: optimize judgment conditions

---

src/million/m.ts

@aidenybai code review, pls.
**Status**

feat: exclude children property

---

src/million/render.ts

if el is null, the diff algorithm gets into trouble
**Status**

feat: check the el is not empty

---

src/million/drivers/useChildren.ts

driver should not handle the empty el.
fixed:
**Status**

feat: driver should not handle empty el

---

src/million/render.ts
src/million/utils.ts

fixed [#209](https://github.com/aidenybai/million/issues/209)
**Status**

feat: clean empty vnode children

---

scripts/welcome.mjs

fix: add id name in welcome/scripts

---

package.json
pnpm-lock.yaml
scripts/helpers.mjs

**Status**
exit(0) is equivalent to exit(EXIT_SUCCESS).
exit(1) is equivalent to exit(EXIT_FAILURE).

fix: exit 1 will break program,

---

website/pages/docs/api/advanced/patch.mdx

Correct spelling and article agreement in `/api/advanced/patch.mdx`.
**Status**

docs: correct typos and article agreement

---

packages/million/scheduler.ts

I've been digging a bit though the code and it has been really easy to follow. I've however noticed a code block that is duplicated inside `million/scheduler.ts`:
Inside `requestAnimationFrame`, the callback:
1) updates `force` and `timer` variables
2) calls `callback()`
I've first noticed that the `reset()` function does the same as 1), and then that `invoke()` does the same as 1) + 2). I was first tempted to refactor to the following:
```ts
requestAnimationFrame(() => invoke())
```
but we can save even more bits by inlining the variable instead of creating a new callback. So not really a bug fix/feature but it should help save a few bits on the final bundle :)
**Status**

refactor: duplicated code inside scheduler

---

website/pages/_document.js

I am sorry. I overlooked a below. Since `icon.png`'s aspect ratio of 1:1, it is necessary that `twitter:card` is `summary`, not `summary_large_image`.
https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary
**Status**

chore: summary_large_image -> summary

---

website/pages/index.mdx

This will remove the h1 from the index page, but keep the correct title
This will preserve the nextra title, without using an h1 to make nextra detect the title. This fixes issue #248 
**Status**

Fix for h1 title

---

.github/CONTRIBUTING.md
benchmarks/package.json
package.json
pnpm-lock.yaml
website/package.json

- Order scripts in the same as in `package.json`
- Add `lint:fix` & `test:dev` explanations
- Add a . at the end of each line
- environment -> environment
**Status**

chore(contributing): fix issues in Scripts section

---

benchmarks/package.json
package.json
packages/million/render.ts
pnpm-lock.yaml

Don't know why CI failed but code seems to run? `pnpm ci-failed-and-i-dont-know-why` is here to save the day
**Status**

feat: ci failed and i don't know why command

---

benchmarks/README.md

docs(benchmarks): fix typo in README.md

---

website/components/Home.js

fix: add space to watch video button

---

README.md

Recently, we've let the hits.link domain expire, mainly because the renew price was $180, so we've resulted to stable and none changing links through vercel's and hop's domains. Sorry for the inconvenience!
**Status**

patch: fix hits counter in readme

---

website/pages/docs/react/block.mdx
website/pages/docs/react/for.mdx

Fix some typos in doc code examples
**Status**

fix typos in doc

---

README.md
packages/react/package.json
pnpm-lock.yaml
website/components/chart.tsx
website/components/home.tsx

Resolves issue #310 
Please review accordingly Maintainers
**Status**

Remove Unnecessary dependencies

---

website/pages/docs/compiler.mdx

Fixed Next.js Config

---

website/pages/docs/index.mdx

Fixes grammar issues in [How does it work?](https://millionjs.org/docs#how-does-it-work) docs' section
**Status**

docs: fix grammar

---

website/pages/blog/virtual-dom.mdx

I have made some grammer fixes for the blog of virtual dom.
**Status**

fix: Fixed grammer for virtual-dom.mdx blog

---

build.config.ts
next.d.ts
package.json
packages/compiler/react.ts
packages/compiler/types.ts
packages/preact-server/README.md
packages/preact-server/index.ts
packages/preact-server/package.json
packages/preact/README.md
packages/preact/block.ts
packages/preact/for.ts
packages/preact/index.ts
packages/preact/package.json
packages/preact/utils.ts
pnpm-lock.yaml
preact-server.d.ts
preact.d.ts
react-server.d.ts
tsconfig.json
website/pages/docs/install.mdx

Adds preact support
**Status**

feat: initial support for preact

---

playground/components/editor.tsx
playground/components/gridResize.tsx
playground/components/monaco-editor.tsx
playground/configurations/nextjs.ts
playground/package.json
pnpm-lock.yaml

- add resizer as same as solid-playground
- add classnames dependencies work with tailwind
- rename next.config.js -> next.config.mjs
**Status**

[playground] resizer and header

---

playground/.swcrc
playground/app/page.tsx
playground/components/client.tsx
playground/components/editor.tsx
playground/components/framework-switcher.tsx
playground/components/gridResize.tsx
playground/package.json
pnpm-lock.yaml

basic framework switcher

---

website/pages/docs/quickstart.mdx

Corrected grammar in quickstart.mdx

---

package.json
packages/compiler/react/transform.ts
packages/compiler/react/utils.ts
packages/million/block.ts
packages/million/dom.ts
packages/million/types.ts
packages/react-server/index.ts
packages/react/block.ts
packages/react/constants.ts
packages/react/for.ts
packages/types/index.ts
website/pages/docs/block.mdx
website/pages/docs/for.mdx
website/pages/docs/internals/string-to-dom.mdx

feat: svg parts

---

website/pages/docs/for.mdx

fix the typo: `rereate` -> `recreate`
**Status**

docs: typo of for.mdx

---

website/components/back-in-block/vdom.tsx
website/pages/blog/virtual-dom.mdx

1. Fixed Typo in  website/components/back-in-block/vdom.tsx
2. Fixed few prepositions and other grammatical issues in website/pages/blog/virtual-dom.mdx
**Status**

docs: Fix typo and few grammatical issues

---

website/pages/docs/internals/patch.mdx
website/pages/docs/internals/render-to-template.mdx
website/pages/docs/rules.mdx

docs: fix website inaccuracies

---

website/pages/docs/install.mdx

fix the typo: [million.vite(), react() }]-> [million.vite(), react()]
**Status**

docs:typo of install.mdx

---

pnpm-lock.yaml
website/components/bounties.tsx
website/components/spotlight.tsx
website/package.json
website/pages/blog/million-v2.5.1.mdx
website/tailwind.config.js

added a grid of cards beneath the callout that displays the 2 most recent bounties (excluding inactive ones)
also revamped the callout and linked it to your bounty board on algora (which displays some extra info like amounts & claims)
always happy to add any other info you'd like to see in your board, but also feel free to revert it back if you prefer otherwise!
Dark | Light
:-----:|:-----:
Dark | Light
:-----:|:-----:
**Status**

feat: add bounty cards

---

build.config.ts
package.json
packages/compiler/plugin.ts
packages/compiler/react/call-expression-visitor.ts
packages/compiler/react/jsx-element-visitor.ts
packages/compiler/react/transform.ts
packages/compiler/react/utils.ts
packages/react-server/index.ts
packages/react/for.ts
packages/react/utils.ts
packages/types/index.ts
pnpm-lock.yaml

hotfix: support for in side for

---

website/pages/blog.mdx

Modified the tabindex to enhance keyboard user experience by reducing redundancy. #432 
**Status**
- [yes ] Code changes have been tested against prettier, or there are no code changes
- [ yes] I know how to update typings and have done so, or typings don't need updating

Feat:removed redundancy for keyboard users

---

website/pages/docs.mdx

A main docs file was added in order to fix the navbar navigation issue
**Status**

Docs page route added

---

packages/kitchen-sink/README.md

In the README, the links did not start with `https://`, so GitHub thought they were part of the repo 🤦🏽
**Status**
- [ x ] Code changes have been tested against prettier, or there are no code changes
- [ x ] I know how to update typings and have done so, or typings don't need updating
- [ x ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

fixed your README links :)

---

packages/compiler/react/evaluator.ts
packages/million/dom.ts
packages/react/for.ts

As per the MIT license
> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
This means just linking to the direct source code is not good enough.
**Status**

chore: Make sure to correctly attribute MIT license

---

website/pages/docs/install.mdx

Fix typo for `conflicts` in docs: install.mdx
**Status**

fix typo for conflicts in docs:install.mdx

---

packages/kitchen-sink/package.json
packages/kitchen-sink/src/examples/carousel.tsx
packages/kitchen-sink/src/style.css
pnpm-lock.yaml

Added a new example for kitchen sink, a vanilla react carousel using an external free image API.
I added just new styles for the carousel in the base kitchen-sink `main.css` file
**Status**

New kitchen sink carousel example added

---

website/theme.config.tsx

This PR fixes the following issues:
fix: #569 
I updated the Twitter logo to the new X logo as part of the company's recent rebranding effort. The new logo is a simple black-and-white "X" instead of the iconic blue and white bird logo. I made this change by replacing the bird svg in theme.config.tsx to a  new svg file.
Screenshot
**Status**

Updated Twitter Icon to X

---

website/components/common-error-video.tsx
website/pages/docs/_meta.json
website/pages/docs/common-errors.mdx

feat: add common errors to docs

---

packages/cli/src/utils/config.ts

**Status**
---
I fixed the code a little bit. Please check it😉

fix(typo): extentions -> extensions

---

website/pages/docs/virtualization.mdx

docs: add bun to @tanstack/react-virtual@beta installation methods

---

build.config.ts
package.json
packages/cli/build.mjs
packages/cli/package.json
packages/cli/src/index.ts
packages/cli/src/utils/modify-config.ts
packages/compiler/plugin.ts
packages/compiler/react/call-expression-visitor.ts
packages/compiler/react/component-visitor.ts
packages/compiler/react/transform.ts
packages/compiler/react/utils.ts
packages/kitchen-sink/src/examples/repro.tsx
packages/react/block.ts
packages/react/constants.ts
pnpm-lock.yaml
website/theme.config.tsx

feat: implement hmr

---

packages/kitchen-sink/package.json
packages/kitchen-sink/src/examples/music-player.jsx
packages/kitchen-sink/src/examples/redux-todo.tsx
packages/kitchen-sink/src/main.tsx
packages/kitchen-sink/src/style.css
packages/kitchen-sink/tsconfig.json
pnpm-lock.yaml

**Status**
Fixes issues #596 and #597

feat: add kitchen sink projects

---

website/pages/blog/_meta.json
website/pages/blog/million-beyond-speed.mdx

PR: Add blog post for comparison between memory usage of React & Million.
**Status**

New blog post - Million Beyond Speed

---

packages/kitchen-sink/package.json
packages/kitchen-sink/src/examples/qr-code-generator.tsx
packages/kitchen-sink/src/style.css
pnpm-lock.yaml

This PR adds a QR code generator to the Kitchen Sink.
Closes #627.
**Status**

feat(sink): qr code generator

---

packages/kitchen-sink/package.json
packages/kitchen-sink/src/examples/canvas.jsx
pnpm-lock.yaml

Added a drawing canvas built using million.js and React. It allows user to use multiple colors for drawing. It also saves the work in localstorage. 
**Status**
Closes: [kitchenSink/Drawing-canvas#619](https://github.com/aidenybai/million/issues/619)

Feature : Add Drawing Canvas.

---

packages/million/block.ts

I just put the duplicate processing into a variable.
**Status**

Variable processing to determine duplicate true/false values

---

website/pages/blog/_meta.json
website/pages/blog/million-hacktoberfest-celebration.mdx

I added an article on how people can contribute to  Million.js this Hacktoberfest.
**Status**

doc: added new article on contributing to hacktoberfest

---

packages/kitchen-sink/src/examples/TicTacToe.jsx

Added a TicTacToe Game built using million.js and React. It allows two users to play the game simultaneously. 
**Status**
closes: [kitchenSink/TicTacToe#648](https://github.com/aidenybai/million/issues/648)

Added Tictactoe Game.

---

packages/kitchen-sink/src/examples/crypto-tracker.jsx

crypto tracker app

---

packages/kitchen-sink/src/examples/locationApp.tsx

This PR aims to demonstrate a location app example using million .
**Status**
Closes : https://github.com/aidenybai/million/issues/610

Kitchen Sink: Build A Location-Based App

---

packages/kitchen-sink/src/examples/news-aggregator.tsx
packages/kitchen-sink/src/style.css

**Added the News-Aggregator App**
**Status**

Added News-Aggregator Component and it's styling

---

packages/kitchen-sink/src/examples/etch-a-sketch.tsx
packages/kitchen-sink/src/style.css

add etch-a-sketch component

---

packages/kitchen-sink/src/examples/rock-paper-scissors.tsx
packages/kitchen-sink/src/style.css

The game gets over if any of the user or the computer reaches 5 points.The user can restart the game anytime.
Resolves #652 
**Status**

Add Rock-Paper-Scissors Game

---

packages/kitchen-sink/src/examples/million_quiz.jsx

Added a file named `million_quiz.jsx` to `packages/kitchen-sink/src/examples`
Used  **Million.js** in it
**Screenshots**
https://github.com/aidenybai/million/assets/119877120/417ad9d9-b5b8-4137-92b2-2ef03941a5c1
**Status**

Added Million.js Quiz Website in Kitchen Sink

---

packages/kitchen-sink/src/examples/quote-generator.tsx

This feature adds a random inspirational quote generator upon click.
Closes #671
**Status**

feat: random inspirational quote generator

---

packages/kitchen-sink/src/examples/pomodoro_timer.jsx

I have built  **Simple Pomodoro Timer app** using react and million.js.
The issue :  #605 
Added a file named `pomodoro_timer.jsx` to `packages/kitchen-sink/src/example`.
I have also used **Million.js** in it.
https://share.zight.com/KouNw1QP

Pomodoro Timer app using react and million.js 

---

packages/kitchen-sink/src/examples/movie-finder.tsx

This PR introduces a new feature in the Kitchen Sink project that enables users to search for movies based on their queries using Million .
Resolves #702 
**Status**

feat: kitchen sink/movie finder

---

packages/kitchen-sink/src/examples/mortgage-calculator.tsx

Added mortgage calculator
Closes #673
**Status**

feat: mortgage calculator

---

packages/kitchen-sink/src/examples/age-calculator.tsx
packages/kitchen-sink/src/style.css

Added an age calculator to the kitchen.
Resolves #743 
**Status**

feat: kitchen sink age calculator

---

packages/kitchen-sink/src/examples/book-recommendation.jsx

features
-fetches data from google books API
-use can select subject of interest
Resolves #628 
**Status**

Book Recommendation kitchen sing

---

.github/stale.yml

chore: exclude issues with "Bounty" from getting stale

---

packages/kitchen-sink/src/examples/discount-calculator.tsx

Added Discount Calculator
Closes #761
**Status**

Feat discount calculator

---

website/pages/docs/install.mdx

The documentation has "yarn create million@latest" instead of "yarn add million@latest" for the installation guide with yarn
**Status**

Update yarn installation guide

---

website/theme.config.tsx

Revert "fix: focus state inconsistency"

---

packages/kitchen-sink/src/main.tsx
packages/kitchen-sink/src/style.css

In this PR, I have Revamped the Kitchen Sink Website to have better User Experience and to look nicer
Resolves #791 
**Status**
Additional Note:
The integration of this ESLint plugin is a crucial step in maintaining and improving the quality of our codebase. I believe that it will have a substantial positive impact on our development process, and I am eager to receive feedback and collaborate with the team to ensure a seamless and productive experience. Thank you for considering this PR.

Revamped the kitchen sink

---

website/theme.config.tsx

fix: system default as the theme mode

---

.github/workflows/labeler.yml

This should fix the immediate issue with the Workflow. Although I suspect there might be another issue which I can only verify after this is merged
**Status**

Fix/workflows: Potential Fix for Labeler

---

.github/workflows/auto-response.yml

I hope this is the last PR I make for this bug. I have tested this in my [fork](https://github.com/haideralipunjabi/million). Created 3 PRs and the action successfully ran on all 3.

Fix or auto-response

---

website/components/ai/hero.tsx
website/styles/global.css

add waitlist component on ai page

add ai waitlist

---

website/pages/docs/install.mdx

I added Remix to the Vite compiler section of the docs, resolves #837 
**Status**

chore: Add Remix To Vite section of docs

---

website/components/home/faq.tsx

chore(faq): update rules of blocks link

---

.github/CONTRIBUTING.md

Resolves #864 raised by @JoshuaKGoldberg. Thanks, Joshua
**Status**

fix: remove invalid information to run the project locally

---

website/pages/blog.es-ES.mdx
website/pages/blog/_meta.es-ES.json
website/pages/blog/million-3.es-ES.mdx
website/pages/blog/million-v2.5.1.es-ES.mdx
website/pages/blog/million-v2.5.3.es-ES.mdx
website/pages/foundation.es-ES.mdx

I'm including the Foundation page translation to Spanish.
**Status**

docs: Translate the Foundation page to Spanish

---

README.md

Original link pointed to non-existent page.
**Status**

Fixed link to docs

---

website/pages/blog.fr-FR.mdx
website/pages/blog/_meta.fr-FR.json
website/pages/blog/behind-the-block.fr-FR.mdx
website/pages/blog/million-3.fr-FR.mdx
website/pages/blog/million-beyond-speed.fr-FR.mdx
website/pages/blog/million-v2.5.1.fr-FR.mdx
website/pages/blog/million-v2.5.3.fr-FR.mdx
website/pages/blog/virtual-dom.fr-FR.mdx
website/pages/docs/_meta.zh-CN.json

**This pull request  add french translation of the blog**
**Status**

docs: translate the blog to french

---

website/components/home/hero.tsx
website/components/wrapped/index.tsx

Basic Analytics

---

packages/telemetry/post.ts

fix: bun installing million issue by polyfilling performance.markResourceTiming

---

packages/compiler/auto.ts
packages/compiler/block.ts
packages/compiler/constants.ts
packages/compiler/utils/ast.ts

Apparently the million ignore functionality is removed and does not work! This tries to implement it again.

fix: million ignore

---

packages/compiler/auto.ts
packages/compiler/block.ts
packages/compiler/plugin.ts
packages/compiler/utils/ast.ts
packages/experimental/index.ts
packages/million/block.ts
packages/react-server/index.ts
packages/react-server/utils.ts
packages/react/block.ts
packages/react/utils.ts
packages/telemetry/post.ts

fix: next14 rsc hydration issue

---

packages/react-server/index.ts
packages/react/its-fine.tsx

Resolves #983 
I was confused since we were facing the same warning in million lint, sorry for that.

fix: useLayouEffect warning
