aidenybai/million

scripts/dev.sh
src/__test__/patch.spec.ts
src/patch.ts

**Description:**
We currently are only iterate through the iterable props but we should iterate over all props...
**Status**

refactor: update patchProps method to pass all props not only iterable ones

---

src/__test__/patch.spec.ts

tests: updating patch tests (patchProps method)

---

src/__test__/createElement.spec.ts
src/createElement.ts

This PR makes some simple improvements for createElement function/tests by increasing readability and turning the function smaller. Also apply some DRY rules to __test__/createElement.
A small performance (time complexity) improvement can be considered since there is only a single call to create an element instead many attributions, also a forEach loop has downsized the needing of some allocations downing the space complexity, but I think these points are tiny and almost imperceptible.
Obs: i didnt created a new build since i dont know if i should do it (?).
**Status**
- [ x ] I know how to update typings and have done so, or typings don't need updating
- [ x ] This PR …

Improvements in tests and readability of createElement fn

---

src/patch.ts

Use Set instead of Array for cache object 
**Status**
Before:
```
list-render:
million x 19,445 ops/sec ±8.47% (16 runs sampled)
virtual-dom x 17,862 ops/sec ±11.48% (44 runs sampled)
vanilla x 8,620 ops/sec ±0.69% (48 runs sampled)
baseline x 14,730 ops/sec ±0.53% (14 runs sampled)
Fastest is million
```
After: 
```
list-render:
million x 28,808 ops/sec ±5.67% (30 runs sampled)
virtual-dom x 19,361 ops/sec ±1.45% (49 runs sampled)
vanilla x 8,621 ops/sec ±0.71% (48 runs sampled)
baseline x 14,591 ops/sec ±0.78% (13 runs sampled)
Fastest is million
```

use cache `Set()` for performance improvement

---

src/million/createElement.ts

fixed: [#191 ]
refer to: [hyperapp](https://github.com/jorgebucaran/hyperapp/blob/main/index.js#L85)
bug fixed.
**Status**

fixed: do not set readonly property.

---

src/million/createElement.ts
test/createElement.test.ts

**Status**
I am using JSX with babel automatic runtime transformation and got `Uncaught TypeError: setting getter-only property "children"`. It is caused by `jsx` function that set `props.children` to `undefined`:
https://github.com/aidenybai/million/blob/e0896e69ecbed516c7e2c77dbe8c0fe7fca0a32e/src/jsx-runtime/jsx.ts#L12
However, `createElement` will always set prop (including `children`) even if the prop is read-only and the prop value is `undefined`. The PR adds an additional `null` and `undefined` check before applying props. The corresponding test case has also been added as well.

fix(createElement): ignore prop value with null and undefined

---

src/jsx-runtime/h.ts

[here](https://github.com/aidenybai/million/blob/main/src/million/m.ts#L107), so in `h` function should not use `svg` again.
is there anything i missing?
**Status**

feat: should not use svg twice.

---

packages/react/exports/jsx-dev-runtime.ts
packages/react/exports/jsx-runtime.ts

Adds missing `Fragment` export to `million/react/jsx-runtime`
**Status**

React jsx runtime export fragment

---

packages/router/router.ts
packages/router/types.ts
pnpm-lock.yaml

Closes #223
Add support for non-text links to be treated as external and reload the page instead of mutating the DOM (`window.location.href = ...`).
`request()` now returns a `Promise<string, Blob>` since the fetched content can be an image, a file... Also, add a property `external` to signify that a `Route` redirects to an URL.
**Status**

feat(router): support non-text links as external

---

website/pages/docs/react/use-list.mdx

Small typo in the docs
**Status**

Fix: small typo

---

website/pages/index.mdx

This should prevent 
from happening
The home page on chrome sometimes displays "Untitled - Million" on the homepage, adding a title to the mdx should make Nextra add the correct title.
**Status**
- [x ] Code changes have been tested against prettier, or there are no code changes
- [ x] I know how to update typings and have done so, or typings don't need updating
- [ x] This PR **only** includes non-code changes, like changes to documentation, README, etc.

Add Home to index page

---

website/pages/docs/api/advanced/flags.mdx

Updates the wording & examples in the "Flags" section ([ref](https://millionjs.org/docs/api/advanced/flags)) of the docs to reflect the available Flags options.
Please let me know if I am incorrect on my understanding that `Flags.ELEMENT_SKIP_DIFF` and `Flags.ELEMENT_FORCE_UPDATE` were intended to have the same functionality.
**Status**

docs: rename ELEMENT_SKIP_DIFF to ELEMENT_FORCE_UPDATE

---

website/pages/blog/virtual-dom.mdx

A small update in the docs:
Line 85: 2. Dirty Checking...
"is diffed the to determine what has changed" should be "is diffed to determine what has changed"

Fix typo in virtual-dom.mdx

---

website/components/home.tsx

Super minor, but makes the entire "Get Started" button on the home page clickable. Without it, one needs to click directly on the text to trigger the link, which is a bit awkward.
**Status**

docs: Make entire "Get Started" link clickable on home page

---

website/pages/docs/render-to-template.mdx

fix: wrong link to `stringToDOM()`

---

website/pages/docs/quickstart.mdx

This pull request aims to improve the installation documentation in the quickstart.mdx file. It addresses two issues identified in the existing documentation:
Problem 1: "Check out the the installation...."
Solution: Removed the duplicate "the" from the sentence to make it more concise and grammatically correct. Updated the sentence to: "Check out the installation..."
Problem 2: "check out the the installation guide...."
Solution: Removed the duplicate "the" from the sentence to enhance readability and consistency. Updated the sentence to: "Check out the installation guide..."
These changes aim to provide clearer instructions and improve the overall quality of the documentation for users who are getting started …

fix-duplicate-words-in-installation-guide-in-quickstart.mdx

---

website/pages/docs/quickstart.mdx

Updates the link to [map-array](https://million.dev/docs/map-array) page from [quickstart](https://million.dev/docs/quickstart) page to point to correct location `/docs/map-array`.
**Status**

docs: fix the link to map-array page from quickstart page

---

website/pages/docs/rules.mdx

Original: Using map() instead of <For />
Changed: Using `<For />` instead of `map()`

Docs: typo

---

packages/compiler/experimental/utils.ts
packages/compiler/react/transform.ts
packages/compiler/react/utils.ts
packages/compiler/react/visitor.ts
packages/react/constants.ts
website/pages/docs/install.mdx

This PR is a mixed bag of changes but mainly:
- We no longer clone the original component. This process is costly since cloning entire components takes time. We now assume that when a user creates a block, it permanently destroys the original component.
- REGISTRY is now DOM API free and can be imported without consequence
- Components are now hoisted. Any bindings are assumed to be accessible in the component scope
**Status**

refactor(compiler): destroy original component to reduce compilation time

---

playground/atoms/framework.ts
playground/components/editor.tsx
playground/components/framework-switcher.tsx
playground/hooks/index.ts
playground/package.json
playground/types.d.ts
pnpm-lock.yaml

Closes #365 
> Got to a decent point, required some kinda wild useEffect stuff to keep the url + atom in sync. Jotai does provide a atomWithHash, but [unfortunately doesn't support Next 13 / app router](https://jotai.org/docs/guides/nextjs#in-next-js-13)
> 
> Also found a bug where if you select a new framework while the current one is loading it will show the new files, but use the previous start command.
> 
> would appreciate any feedback on what I did so far. Thanks!
through some git stuff I dont understand the first pr got closed but at least now its synced with the the current state of the playground branch

Playground: Preset Passed Via Search Param in URL

---

website/pages/docs/install.mdx

This PR updates the documentation to resolve an issue ( #405 ) where the Vite plugin order between MillionJS and React plugin caused the application to fail. The React plugin was modifying the AST before MillionJS could compile the components, changing their structure. By explicitly setting the enforce property to 'default' for the React plugin in the documentation, we ensure that the MillionJS compiler runs first, resolving the issue.
**Status**

Update documentation to resolve Vite plugin order issue

---

package.json
pnpm-lock.yaml

This PR updates the TypeScript version from 4.9.5 to 5.1.3. This change has been made at the turborepo root in the devDependencies, so it should not affect the actual operation. This is just a small maintenance update to keep our development environment up to date.
**Status**

Update TypeScript version from 4.9.5 to 5.1.3

---

packages/compiler/react/transform.ts
packages/compiler/react/visitor.ts

This PR fixes importing `{ For, block }` not transforming, and removes `__props` when there are no props.
**Status**

fix: allow importing both for and block + flaatten no props

---

website/pages/docs/install.mdx

**Status**
----
The existing suggested enforce type is incorrect as the latest Vite does not support default type and only supports `"pre"` or `"post"`.
This pull request changes it to use defaults instead, similar to the examples later in the docs 
https://github.com/aidenybai/million/blob/main/website/components/box.tsx#L108
Both the website and apps with the new config work fine

Docs fix: Installation/Vite - Incorrect enforce type in Vite config

---

package.json
packages/compiler/plugin.ts
packages/compiler/react/call-expression-visitor.ts
packages/compiler/react/evaluator.ts
packages/compiler/react/index.ts
packages/compiler/react/jsx-element-visitor.ts
packages/compiler/react/transform.ts
packages/compiler/react/types.ts
packages/compiler/react/utils.ts
packages/compiler/react/visitor.ts
packages/million/template.ts
packages/react/block.ts
packages/react/for.ts
packages/react/index.ts
pnpm-lock.yaml
website/pages/docs/macro.mdx

Introduces macro functionality and pre-evaluation within `JSXContainerExpressions`
```js
```jsx
import { macro } from 'million/react';
const fib = (n) => {
if (n <= 1) return 1;
return fib(n - 1) + fib(n - 2);
};
const value = macro(fib(10)); // 55
```
**Status**

feat: macros

---

website/styles/global.css

I followed instructions from https://github.com/pacocoursey/next-themes#without-css-variables to fix flashing. Now instead of seeing a quick white screen flash into your eyes when you open the site, the background will stay dark.
**Status**

Fix 529: Background screen flash on reload

---

packages/kitchen-sink/src/main.tsx
packages/react/utils.ts
website/components/million-library/react.cjs
website/components/million-library/react.mjs

fix #534
/claim #534
**Status**

version on react + run prettier

---

packages/compiler/react/evaluator.ts

This PR extends the existing JSX binary operations evaluation functionality.
- Added evaluation support for relational operators (`<`, `>`, `<=`, `>=`).
- Added evaluation support for equality operators (`==`, `!=`, `===`, `!==`).
**Status**

Extend JSX Binary Operations Evaluation

---

packages/compiler/plugin.ts

fixes https://github.com/aidenybai/million/issues/532
Instead of relying on the string path for the plugin let's import the babel plugin directly. This should hopefully be more robust.
**Status**

fix(compiler): Directly import babel plugins

---

packages/compiler/react/transform.ts

I removed needless `spread`, because `map` already created new array.
**Status**

fix: remove needless spread in transform

---

packages/kitchen-sink/src/examples/redux-todo.tsx
packages/kitchen-sink/src/examples/weather-app.tsx
packages/kitchen-sink/src/main.tsx

I have made a weather app which shows the temperature of the city entered along with the weather description . It is done in typescript and all the correct methods are followed .
If you want any changes please inform me :)
**Status**

Weather App

---

packages/kitchen-sink/src/examples/guestbook.tsx

Added Guestbook components in Kitchen Sink
Status
- [ x] Code changes have been tested against prettier, or there are no code changes
- [ x] I know how to update typings and have done so, or typings don't need updating
- [x ] This PR changes the codebase
- [ x] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)

added guestbook

---

packages/kitchen-sink/package.json
packages/kitchen-sink/src/examples/emoji-picker.tsx
pnpm-lock.yaml

In this PR, I have implemented a feature that allows users to insert emojis in between their text input using React, million.js, and TypeScript. This feature enhances the user experience by adding a fun and expressive way to convey emotions and reactions in text.
- **Improved User Experience:** Emojis are a widely recognized form of expression in modern communication. By enabling users to easily insert emojis into their text input, we enhance the overall user experience and make the application more engaging and user-friendly.
- **Expressive Communication:** Emojis provide a way for users to convey emotions and reactions effectively, which is particularly important in social or messaging applications. This feature enables users to express themselves more authentically.
- **Bug-Free …

Emoji picker added

---

packages/kitchen-sink/src/examples/password-generator.tsx
packages/kitchen-sink/src/style.css
pnpm-lock.yaml

In this PR, I have implemented a feature that allows users to generate passswords based on the user options using React, million.js, and TypeScript. This feature enhances Security for password based authentication systems.
Enhanced Security: Passwords play a fundamental role in securing user accounts and sensitive data. A built-in password generator ensures that users can easily create strong and complex passwords, improving the overall security posture of our application.
Usability: Complex password requirements are common in many systems today. By providing a password generator, we enhance the user experience by simplifying the process of creating strong passwords. Users no longer need to rely on memorizing or manually generating secure passwords.
Compliance: In various industries, …

Password generator

---

packages/kitchen-sink/src/examples/hangman-game.tsx

issue #675 
**Description**
I have developed and thoroughly tested the Hangman game, and it's fully functional and ready for review.
**Game Features:**
- **Hint Display:** Users are presented with a hint for the word they need to guess.
- **Word Guessing:** Users are required to guess the word based on the given hint.
- **Incorrect Guess Handling:** Incorrect guesses lead to the gradual creation of the hangman figure.
- **Loss Condition:** If the hangman figure is completed, the user loses the game.
- **Win Condition:** Upon successful completion, the user can reset the game and receive a new word to guess.
**Screenshots:**
<br/>
<h3> I am in the process of creating a pull request for this feature. Your feedback is welcome! </h3>
<hr/>
**Status**

Hangman game

---

packages/kitchen-sink/src/examples/expense-tracker.tsx

This PR adds **Expense tracker** example to the list of Kitchen Sink examples as per #606 
I ran the `pnpm cleanup` command and it modified a lot of files, but I only pushed the changes for this project file and nothing more, hope thats okay. 
The `pnpm lint` and `pnpm test` command and all seems OK. 
My knowledge of TS and million is very basic so please recommend fixes as needed. 
If there is any missing feature in the current implementation of the project or some logic that seems odd or need fixing, I am ready to work on it as needed. 
Thank you.
**Status**

feat: add expense tracker to kitchen skin

---

packages/kitchen-sink/src/examples/dice-roller.tsx
packages/kitchen-sink/src/style.css

Added dice roller app feature with nice CSS effect.
Closes #672
**Status**
- [x ] Code changes have been tested against prettier, or there are no code changes
- [x ] I know how to update typings and have done so, or typings don't need updating

feat: dice roller feature

---

packages/kitchen-sink/src/examples/GithubUserSearch.jsx

This PR adds a new feature to the application that allows users to search for GitHub users and view their profiles. Additionally, it enhances the user profile functionality by displaying the user's followers, following, location, and bio.
Added a new search feature that allows users to search for GitHub users by their username.
Implemented the search functionality using the GitHub API.
Display search results with user avatars and usernames.
Clicking on a search result takes the user to the corresponding user's profile page.
User Profile Enhancement:
On the user profile page, added a section to display the user's followers and following counts.
Display the user's location and bio if available in their GitHub profile.
Screenshots:
Performed unit tests for the search functionality.
Manually …

Added github user search

---

packages/kitchen-sink/src/examples/VocabularyQuiz.tsx

Created a vocabulary quiz game with flash card and **million.js**. This issue is for [ hacktober fest](https://hacktoberfest.com/)
[scrnli_10_8_2023_11-52-39 PM.webm](https://github.com/aidenybai/million/assets/20371014/cdf442b9-e43f-4558-8da2-69cc14a69cae)
**Status**
Solves **Issue**    #618 
- [] This PR changes the codebase
- [] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)
- [] This PR **only** includes non-code changes, like changes to documentation, README, etc.

Kitchen Sink: Build A Flashcard Vocabulary Game #618

---

packages/kitchen-sink/src/examples/interactive-card-game.tsx
packages/kitchen-sink/src/style.css

**Status**
last PR had some conflicts so created a new PR
this PR resolves issue #701

created interactive-card-game

---

packages/kitchen-sink/src/examples/virtualWhiteboard.tsx

Designed and created a virtual whiteboard with in React-TS with Million.js, that allows the user to select their input color and the modes: draw, write, line, erase, undo, and redo. This fulfills the criteria laid out in #613, as part of Million.js 's Hacktoberfest event.
I made a further commit to resolve issues with the way the color input button was being rendered in Chrome vs Firefox. In Chrome, padding was being added by default that crushed the visibility of the selected color inside of the button. I added values specific to Chrome and Firefox to make the button look similar between the two browsers for a more consistent user experience.
**Status**

Build a virtual whiteboard 613

---

packages/kitchen-sink/src/examples/minesweeper.jsx

resolves #724 
**Description**
I have developed and tested the Minesweeper game. It is fully functional and ready for review.
**Game Features**
- A minesweeper game with its main goal to clear a rectangular board containing hidden "mines" or bombs without detonating any of them.
- Allow users to choose the difficulty level of the game, such as 1,2,3....7. According to which grid size and number of mines 
changes.
-  If the user opens a cell with a bomb, display a loss message in a toast notification.
- Allow users to reset game with help of a reset button.
**Below are some Screenshots and video of the game-**
https://github.com/aidenybai/million/assets/119878088/07dca57a-411b-474a-9f94-759aafec55de
<h3>I am in the process of creating a pull request for this feature. Your feedback is …

Minesweeper game is developed

---

packages/kitchen-sink/src/examples/investment-calculator.tsx

Added Investment Calculator
Resolves #765
**Status**

feat: Investment Calculator

---

website/theme.config.tsx

fixes #641 
I have updated the nextra theme config, by changing primary hue for the dark mode.
This is the colour I picked according to the theme:
**Status**

fix: focus state inconsistency

---

packages/kitchen-sink/src/examples/data-converter.tsx

Added Data Converter in Kitchen Sink
Resolves #764
**Status**

feat: Added Data Converter in Kitchen Sink

---

website/components/extra-content.tsx

Simple fix: when there is only a single user online on a page, use "user" instead of "users" so we don't end up with "1 users connected"
**Status**

Fix plurality of "users" in status

---

.github/workflows/auto-response.yml

Fix/Workflows: Auto Response Workflow

---

.github/workflows/auto-response.yml

As per this [documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) `pull_request_target` is used for: 
> This event allows your workflow to do things like label or comment on pull requests from forks.

Fix for Auto Response Action

---

packages/kitchen-sink/src/examples/todolist.tsx

Two important bugs were resolved, one to correctly clear the input after adding a new task and the other related to an items deletion issue
**Status**

Kitchen Sink: Todolist bugs fixed

---

packages/cli/src/utils/modify-config.ts
pnpm-lock.yaml

**Status**
I abstracted the return logic for writing into the config file in all cases into helper functions

refactor: export code wrapper in modify-config

---

website/pages/blog/virtual-dom.mdx
website/styles/global.css

The YouTube embed on the "Back in Block" blog post looks broken on mobile:
This is actually already fixed on the `/ai` page. This PR brings that fix over to this blog post.
It also uses the `aspect-ratio` CSS property, which is now supported in all major browsers.
**Status**

fix(website): youtube embed component mobile sizing

---

packages/compiler/react/utils.ts

In the current cli, the warning message for following some rules has a link to the wrong URL [](https://million.dev/docs/rules) so i updated it to the correct URL [](https://million.dev/docs/manual-mode/block#rules-of-blocks)
**Status**

chore: updated cli docs url

---

packages/million/block.ts

A small typo fix discovered on stream with @tobySolutions 🙂 
**Status**
- ~[ ] This PR changes the codebase~
- ~[ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)~
- ~[ ] This PR changes the internal workings with no modifications to the external API (bug fixes, performance improvements)~

docs: fix 'cooresponding'/'corresponding' typo

---

packages/react/block.ts
packages/react/compiled-block.ts

Fixes the unintentional unique `key` error thrown by React because of `block`
- Fixes #942

fix: unique `key` error

---

packages/compiler/plugin.ts

Resolves #878 
Now we return an empty file so we do not break the cycle for next updates. This might not be the ideal solution since I'm not as expert as @lxsmnsyc on the compiler, but it worked.

fix: nextjs hmr on error

---

packages/react-server/index.ts

Resolves #987 
I don't understand how remix spa behaves under the hood since vite is informing us that it's a server build, but still, it's not getting SSRed.
What I did here is just not throwing error when there's no ssr content.

fix: remix spa

---

website/pages/blog/behind-the-block.en-US.mdx
website/pages/blog/behind-the-block.es-ES.mdx
website/pages/blog/behind-the-block.fr-FR.mdx
website/pages/blog/behind-the-block.zh-CN.mdx

I was reading the docs and noticed that this link was outdated.
**Status**

fix: broken `block` link

---

packages/million/alias.ts
packages/million/template.ts
test/alias.test.ts

Fixes #996.
As this resolves unintended behavior, but technically does change the output of the generated HTML, it is up to you if you want to consider this as a breaking change or not.
**Status**

fix: #996 Handle property alias

---

packages/compiler/auto.ts
packages/compiler/plugin.ts
packages/compiler/utils/log.ts

There was a confusing behavior caused by the strange logic in the compiler logging.
It is possible to turn off the logging only if the `log` option has been set to a truthy value, which is not equal to `'info'`, because of the condition `!ctx.options.log || ctx.options.log === 'info'`.
However, at the same time, the type of the `log` option is either `boolean | 'info' | undefined`, so there is no valid value with type that can turn off the logging.
I think that this PR will make the logic of the `log` option a little clearer.
**Status**

fix: `log` compiler option
